spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: true

sdk:
  domain: https://open-api.hailuo.pro
  secretKey: WkYe28Hlu0N1n6YRx/pWww==
  iv: TDuZJVSOiSrXMbdsYGU03w==
partner:
  domain: 
  secretKey: 
  iv: 
server:
  port: 8889


swagger:
  enabled: true

logging:
  file: /home/lxtx/logs/hello/hello-sdk-demo/hello-sdk-demo